[2023-11-14T11:21:06.441+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_dag.transform_task manual__2023-11-14T11:21:00.742025+00:00 [queued]>
[2023-11-14T11:21:06.447+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_dag.transform_task manual__2023-11-14T11:21:00.742025+00:00 [queued]>
[2023-11-14T11:21:06.448+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-14T11:21:06.448+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-14T11:21:06.448+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-14T11:21:06.498+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): transform_task> on 2023-11-14 11:21:00.742025+00:00
[2023-11-14T11:21:06.504+0000] {standard_task_runner.py:55} INFO - Started process 22555 to run task
[2023-11-14T11:21:06.509+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'transform_dag', 'transform_task', 'manual__2023-11-14T11:21:00.742025+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/transform_dag.py', '--cfg-path', '/tmp/tmpp4p1q2by']
[2023-11-14T11:21:06.511+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask transform_task
[2023-11-14T11:21:06.698+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_dag.transform_task manual__2023-11-14T11:21:00.742025+00:00 [running]> on host codespaces-1a8ad4
[2023-11-14T11:21:06.976+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=transform_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2023-11-14T11:21:00.742025+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-14T11:21:00.742025+00:00
[2023-11-14T11:21:06.983+0000] {logging_mixin.py:137} WARNING - /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/transform_dag.py:19 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-11-14T11:21:06.988+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-11-14T11:21:06.991+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=transform_dag, task_id=transform_task, execution_date=20231114T112100, start_date=20231114T112106, end_date=20231114T112106
[2023-11-14T11:21:07.080+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-11-14T11:21:07.089+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
